
FROM likechain/abci as builder

# Copy files to WORKDIR
COPY . ./

# Build executables
RUN go build -a -o /bin/likechain/abci cmd/abci/main.go
RUN go build -a -o /bin/likechain/api cmd/api/main.go

FROM alpine:latest

WORKDIR /bin/likechain/

COPY --from=builder /bin/likechain/abci .
COPY --from=builder /bin/likechain/api .

CMD ["./abci"]
