// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: likenft/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	nft "github.com/likecoin/likechain/backport/cosmos-sdk/v0.46.0-alpha2/x/nft"
	types "github.com/likecoin/likechain/x/iscn/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryClassesByISCNRequest struct {
	IscnIdPrefix string             `protobuf:"bytes,1,opt,name=iscnIdPrefix,proto3" json:"iscnIdPrefix,omitempty"`
	Pagination   *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryClassesByISCNRequest) Reset()         { *m = QueryClassesByISCNRequest{} }
func (m *QueryClassesByISCNRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClassesByISCNRequest) ProtoMessage()    {}
func (*QueryClassesByISCNRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{2}
}
func (m *QueryClassesByISCNRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClassesByISCNRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClassesByISCNRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClassesByISCNRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassesByISCNRequest.Merge(m, src)
}
func (m *QueryClassesByISCNRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryClassesByISCNRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassesByISCNRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassesByISCNRequest proto.InternalMessageInfo

func (m *QueryClassesByISCNRequest) GetIscnIdPrefix() string {
	if m != nil {
		return m.IscnIdPrefix
	}
	return ""
}

func (m *QueryClassesByISCNRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryClassesByISCNResponse struct {
	IscnIdPrefix string              `protobuf:"bytes,1,opt,name=iscnIdPrefix,proto3" json:"iscnIdPrefix,omitempty"`
	Classes      []nft.Class         `protobuf:"bytes,2,rep,name=classes,proto3" json:"classes"`
	Pagination   *query.PageResponse `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryClassesByISCNResponse) Reset()         { *m = QueryClassesByISCNResponse{} }
func (m *QueryClassesByISCNResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClassesByISCNResponse) ProtoMessage()    {}
func (*QueryClassesByISCNResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{3}
}
func (m *QueryClassesByISCNResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClassesByISCNResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClassesByISCNResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClassesByISCNResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassesByISCNResponse.Merge(m, src)
}
func (m *QueryClassesByISCNResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryClassesByISCNResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassesByISCNResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassesByISCNResponse proto.InternalMessageInfo

func (m *QueryClassesByISCNResponse) GetIscnIdPrefix() string {
	if m != nil {
		return m.IscnIdPrefix
	}
	return ""
}

func (m *QueryClassesByISCNResponse) GetClasses() []nft.Class {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *QueryClassesByISCNResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryClassesByISCNIndexRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryClassesByISCNIndexRequest) Reset()         { *m = QueryClassesByISCNIndexRequest{} }
func (m *QueryClassesByISCNIndexRequest) String() string { return proto.CompactTextString(m) }
func (*QueryClassesByISCNIndexRequest) ProtoMessage()    {}
func (*QueryClassesByISCNIndexRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{4}
}
func (m *QueryClassesByISCNIndexRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClassesByISCNIndexRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClassesByISCNIndexRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClassesByISCNIndexRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassesByISCNIndexRequest.Merge(m, src)
}
func (m *QueryClassesByISCNIndexRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryClassesByISCNIndexRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassesByISCNIndexRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassesByISCNIndexRequest proto.InternalMessageInfo

func (m *QueryClassesByISCNIndexRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryClassesByISCNIndexResponse struct {
	ClassesByISCN []ClassesByISCN     `protobuf:"bytes,1,rep,name=classesByISCN,proto3" json:"classesByISCN"`
	Pagination    *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryClassesByISCNIndexResponse) Reset()         { *m = QueryClassesByISCNIndexResponse{} }
func (m *QueryClassesByISCNIndexResponse) String() string { return proto.CompactTextString(m) }
func (*QueryClassesByISCNIndexResponse) ProtoMessage()    {}
func (*QueryClassesByISCNIndexResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{5}
}
func (m *QueryClassesByISCNIndexResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryClassesByISCNIndexResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryClassesByISCNIndexResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryClassesByISCNIndexResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryClassesByISCNIndexResponse.Merge(m, src)
}
func (m *QueryClassesByISCNIndexResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryClassesByISCNIndexResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryClassesByISCNIndexResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryClassesByISCNIndexResponse proto.InternalMessageInfo

func (m *QueryClassesByISCNIndexResponse) GetClassesByISCN() []ClassesByISCN {
	if m != nil {
		return m.ClassesByISCN
	}
	return nil
}

func (m *QueryClassesByISCNIndexResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryISCNByClassRequest struct {
	ClassId string `protobuf:"bytes,1,opt,name=classId,proto3" json:"classId,omitempty"`
}

func (m *QueryISCNByClassRequest) Reset()         { *m = QueryISCNByClassRequest{} }
func (m *QueryISCNByClassRequest) String() string { return proto.CompactTextString(m) }
func (*QueryISCNByClassRequest) ProtoMessage()    {}
func (*QueryISCNByClassRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{6}
}
func (m *QueryISCNByClassRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryISCNByClassRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryISCNByClassRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryISCNByClassRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryISCNByClassRequest.Merge(m, src)
}
func (m *QueryISCNByClassRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryISCNByClassRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryISCNByClassRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryISCNByClassRequest proto.InternalMessageInfo

func (m *QueryISCNByClassRequest) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

type QueryISCNByClassResponse struct {
	IscnIdPrefix  string                    `protobuf:"bytes,1,opt,name=iscnIdPrefix,proto3" json:"iscnIdPrefix,omitempty"`
	Owner         string                    `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	LatestVersion uint64                    `protobuf:"varint,3,opt,name=latestVersion,proto3" json:"latestVersion,omitempty"`
	LatestRecord  types.QueryResponseRecord `protobuf:"bytes,4,opt,name=latestRecord,proto3" json:"latestRecord"`
}

func (m *QueryISCNByClassResponse) Reset()         { *m = QueryISCNByClassResponse{} }
func (m *QueryISCNByClassResponse) String() string { return proto.CompactTextString(m) }
func (*QueryISCNByClassResponse) ProtoMessage()    {}
func (*QueryISCNByClassResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{7}
}
func (m *QueryISCNByClassResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryISCNByClassResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryISCNByClassResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryISCNByClassResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryISCNByClassResponse.Merge(m, src)
}
func (m *QueryISCNByClassResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryISCNByClassResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryISCNByClassResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryISCNByClassResponse proto.InternalMessageInfo

func (m *QueryISCNByClassResponse) GetIscnIdPrefix() string {
	if m != nil {
		return m.IscnIdPrefix
	}
	return ""
}

func (m *QueryISCNByClassResponse) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *QueryISCNByClassResponse) GetLatestVersion() uint64 {
	if m != nil {
		return m.LatestVersion
	}
	return 0
}

func (m *QueryISCNByClassResponse) GetLatestRecord() types.QueryResponseRecord {
	if m != nil {
		return m.LatestRecord
	}
	return types.QueryResponseRecord{}
}

type QueryGetClassesByAccountRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *QueryGetClassesByAccountRequest) Reset()         { *m = QueryGetClassesByAccountRequest{} }
func (m *QueryGetClassesByAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetClassesByAccountRequest) ProtoMessage()    {}
func (*QueryGetClassesByAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{8}
}
func (m *QueryGetClassesByAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClassesByAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClassesByAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClassesByAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClassesByAccountRequest.Merge(m, src)
}
func (m *QueryGetClassesByAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClassesByAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClassesByAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClassesByAccountRequest proto.InternalMessageInfo

func (m *QueryGetClassesByAccountRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type QueryGetClassesByAccountResponse struct {
	ClassesByAccount ClassesByAccount `protobuf:"bytes,1,opt,name=classesByAccount,proto3" json:"classesByAccount"`
}

func (m *QueryGetClassesByAccountResponse) Reset()         { *m = QueryGetClassesByAccountResponse{} }
func (m *QueryGetClassesByAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetClassesByAccountResponse) ProtoMessage()    {}
func (*QueryGetClassesByAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{9}
}
func (m *QueryGetClassesByAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetClassesByAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetClassesByAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetClassesByAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetClassesByAccountResponse.Merge(m, src)
}
func (m *QueryGetClassesByAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetClassesByAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetClassesByAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetClassesByAccountResponse proto.InternalMessageInfo

func (m *QueryGetClassesByAccountResponse) GetClassesByAccount() ClassesByAccount {
	if m != nil {
		return m.ClassesByAccount
	}
	return ClassesByAccount{}
}

type QueryAllClassesByAccountRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllClassesByAccountRequest) Reset()         { *m = QueryAllClassesByAccountRequest{} }
func (m *QueryAllClassesByAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllClassesByAccountRequest) ProtoMessage()    {}
func (*QueryAllClassesByAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{10}
}
func (m *QueryAllClassesByAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllClassesByAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllClassesByAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllClassesByAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllClassesByAccountRequest.Merge(m, src)
}
func (m *QueryAllClassesByAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllClassesByAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllClassesByAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllClassesByAccountRequest proto.InternalMessageInfo

func (m *QueryAllClassesByAccountRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllClassesByAccountResponse struct {
	ClassesByAccount []ClassesByAccount  `protobuf:"bytes,1,rep,name=classesByAccount,proto3" json:"classesByAccount"`
	Pagination       *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllClassesByAccountResponse) Reset()         { *m = QueryAllClassesByAccountResponse{} }
func (m *QueryAllClassesByAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllClassesByAccountResponse) ProtoMessage()    {}
func (*QueryAllClassesByAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af5bbcbe472f31b2, []int{11}
}
func (m *QueryAllClassesByAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllClassesByAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllClassesByAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllClassesByAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllClassesByAccountResponse.Merge(m, src)
}
func (m *QueryAllClassesByAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllClassesByAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllClassesByAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllClassesByAccountResponse proto.InternalMessageInfo

func (m *QueryAllClassesByAccountResponse) GetClassesByAccount() []ClassesByAccount {
	if m != nil {
		return m.ClassesByAccount
	}
	return nil
}

func (m *QueryAllClassesByAccountResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "likecoin.likechain.likenft.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "likecoin.likechain.likenft.QueryParamsResponse")
	proto.RegisterType((*QueryClassesByISCNRequest)(nil), "likecoin.likechain.likenft.QueryClassesByISCNRequest")
	proto.RegisterType((*QueryClassesByISCNResponse)(nil), "likecoin.likechain.likenft.QueryClassesByISCNResponse")
	proto.RegisterType((*QueryClassesByISCNIndexRequest)(nil), "likecoin.likechain.likenft.QueryClassesByISCNIndexRequest")
	proto.RegisterType((*QueryClassesByISCNIndexResponse)(nil), "likecoin.likechain.likenft.QueryClassesByISCNIndexResponse")
	proto.RegisterType((*QueryISCNByClassRequest)(nil), "likecoin.likechain.likenft.QueryISCNByClassRequest")
	proto.RegisterType((*QueryISCNByClassResponse)(nil), "likecoin.likechain.likenft.QueryISCNByClassResponse")
	proto.RegisterType((*QueryGetClassesByAccountRequest)(nil), "likecoin.likechain.likenft.QueryGetClassesByAccountRequest")
	proto.RegisterType((*QueryGetClassesByAccountResponse)(nil), "likecoin.likechain.likenft.QueryGetClassesByAccountResponse")
	proto.RegisterType((*QueryAllClassesByAccountRequest)(nil), "likecoin.likechain.likenft.QueryAllClassesByAccountRequest")
	proto.RegisterType((*QueryAllClassesByAccountResponse)(nil), "likecoin.likechain.likenft.QueryAllClassesByAccountResponse")
}

func init() { proto.RegisterFile("likenft/query.proto", fileDescriptor_af5bbcbe472f31b2) }

var fileDescriptor_af5bbcbe472f31b2 = []byte{
	// 849 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x4f, 0x13, 0x5d,
	0x14, 0xee, 0x2d, 0x1f, 0xef, 0xcb, 0x05, 0x12, 0x72, 0x69, 0xf2, 0x96, 0x09, 0x6f, 0x69, 0x46,
	0xa2, 0x88, 0x32, 0x23, 0x54, 0x88, 0x02, 0x0b, 0x28, 0x89, 0xa4, 0x0b, 0x0d, 0xd6, 0xa8, 0x89,
	0x0b, 0xc9, 0x74, 0x7a, 0x5b, 0x26, 0x0e, 0x73, 0x4b, 0x67, 0xaa, 0x34, 0x84, 0x0d, 0x1b, 0xb7,
	0x26, 0xc6, 0x9f, 0xe2, 0x0f, 0xd0, 0xb8, 0xc0, 0xb8, 0x90, 0xc4, 0x8d, 0x2b, 0x63, 0xc0, 0xdf,
	0x61, 0xcc, 0xdc, 0x7b, 0x6e, 0x9d, 0xe9, 0x77, 0x1b, 0x76, 0xf7, 0xe3, 0x3c, 0xe7, 0x3c, 0xcf,
	0x33, 0xa7, 0xe7, 0x16, 0x4f, 0xda, 0xd6, 0x0b, 0xea, 0x14, 0x3c, 0xfd, 0xa0, 0x42, 0xcb, 0x55,
	0xad, 0x54, 0x66, 0x1e, 0x23, 0x8a, 0x7f, 0x68, 0x32, 0xcb, 0xd1, 0xf8, 0x62, 0xcf, 0x80, 0x95,
	0x53, 0xf0, 0x94, 0x58, 0x91, 0x15, 0x19, 0x0f, 0xd3, 0xfd, 0x95, 0x40, 0x28, 0xd3, 0x45, 0xc6,
	0x8a, 0x36, 0xd5, 0x8d, 0x92, 0xa5, 0x1b, 0x8e, 0xc3, 0x3c, 0xc3, 0xb3, 0x98, 0xe3, 0xc2, 0xed,
	0xbc, 0xc9, 0xdc, 0x7d, 0xe6, 0xea, 0x39, 0xc3, 0xa5, 0xa2, 0x90, 0xfe, 0x72, 0x31, 0x47, 0x3d,
	0x63, 0x51, 0x2f, 0x19, 0x45, 0xcb, 0xe1, 0xc1, 0x10, 0x1b, 0x93, 0x84, 0x4a, 0x46, 0xd9, 0xd8,
	0x97, 0x19, 0xfe, 0x97, 0xa7, 0xa6, 0x6d, 0xb8, 0x2e, 0x75, 0x77, 0x73, 0xd5, 0x5d, 0xcb, 0x35,
	0x25, 0x68, 0x1a, 0x0a, 0xf8, 0x11, 0x32, 0xb3, 0x53, 0xf0, 0xe0, 0x36, 0xd9, 0x04, 0x6c, 0x98,
	0x26, 0xab, 0x38, 0x32, 0x62, 0xc2, 0xcf, 0x15, 0xb4, 0x40, 0x8d, 0x61, 0xf2, 0xd0, 0xdf, 0xee,
	0x70, 0x16, 0x59, 0x7a, 0x50, 0xa1, 0xae, 0xa7, 0x3e, 0xc5, 0x93, 0xa1, 0x53, 0xb7, 0xc4, 0x1c,
	0x97, 0x92, 0x0d, 0x3c, 0x2c, 0xd8, 0xc6, 0x51, 0x12, 0xcd, 0x8d, 0x2e, 0xa9, 0x5a, 0x6b, 0x03,
	0x35, 0x81, 0x4d, 0x0f, 0x9e, 0xfe, 0x98, 0x89, 0x64, 0x01, 0xa7, 0xbe, 0x46, 0x78, 0x8a, 0x67,
	0xde, 0x12, 0x14, 0xd3, 0xd5, 0xcc, 0xa3, 0xad, 0x07, 0x50, 0x96, 0xa8, 0x78, 0xcc, 0x27, 0x98,
	0xc9, 0xef, 0x94, 0x69, 0xc1, 0x3a, 0xe4, 0x55, 0x46, 0xb2, 0xa1, 0x33, 0x72, 0x0f, 0xe3, 0xbf,
	0x5e, 0xc6, 0xa3, 0x9c, 0xc7, 0x55, 0x4d, 0xf8, 0xa2, 0xf9, 0xc6, 0x6b, 0x42, 0x1e, 0xd8, 0xa3,
	0xed, 0x18, 0x45, 0x0a, 0xf9, 0xb3, 0x01, 0xa4, 0xfa, 0x09, 0x61, 0xa5, 0x19, 0x13, 0x90, 0xda,
	0x0d, 0x95, 0xbb, 0xf8, 0x1f, 0x70, 0x3a, 0x1e, 0x4d, 0x0e, 0xcc, 0x8d, 0x2e, 0x4d, 0x49, 0x1e,
	0xbe, 0x7e, 0x49, 0x80, 0xe7, 0x07, 0x1b, 0x64, 0x3c, 0xd9, 0x0e, 0xa9, 0x18, 0xe0, 0x2a, 0xae,
	0x75, 0x54, 0x21, 0xb8, 0x85, 0x64, 0xec, 0xe1, 0x44, 0xa3, 0x8a, 0x8c, 0x93, 0xa7, 0x87, 0xd2,
	0xd4, 0xb0, 0x61, 0xa8, 0x6f, 0xc3, 0x3e, 0x20, 0x3c, 0xd3, 0xb2, 0x14, 0xb8, 0xf6, 0x18, 0x8f,
	0x9b, 0xc1, 0xdb, 0x38, 0xe2, 0xbe, 0x5c, 0x6f, 0xd7, 0x27, 0xa1, 0x74, 0xe0, 0x53, 0x38, 0x4b,
	0x9d, 0x5b, 0xd1, 0xfe, 0xdd, 0x4a, 0xe1, 0xff, 0xb8, 0x04, 0x5e, 0x4a, 0x08, 0x91, 0x36, 0xc5,
	0xe1, 0x63, 0x66, 0xf2, 0xf0, 0xad, 0xe5, 0x56, 0xfd, 0x8c, 0x70, 0xbc, 0x11, 0xd5, 0x43, 0x9f,
	0xc4, 0xf0, 0x10, 0x7b, 0xe5, 0xd0, 0x32, 0x67, 0x3e, 0x92, 0x15, 0x1b, 0x32, 0x8b, 0xc7, 0x6d,
	0xc3, 0xa3, 0xae, 0xf7, 0x84, 0x96, 0x5d, 0xd9, 0x05, 0x83, 0xd9, 0xf0, 0x21, 0xb9, 0x8f, 0xc7,
	0xc4, 0x41, 0x96, 0x9a, 0xac, 0x9c, 0x8f, 0x0f, 0x72, 0xf1, 0x57, 0x02, 0x3e, 0xf2, 0xf1, 0xc0,
	0xf9, 0xd5, 0x24, 0xf3, 0x50, 0xb0, 0x32, 0x04, 0x57, 0xd7, 0xe0, 0x1b, 0x6e, 0x53, 0xaf, 0xe6,
	0xfb, 0xa6, 0x18, 0x11, 0x01, 0x23, 0x60, 0x68, 0x48, 0x23, 0x60, 0xab, 0x9e, 0x20, 0x9c, 0x6c,
	0x8d, 0x06, 0x43, 0x9e, 0xe3, 0x09, 0xb3, 0xee, 0x0e, 0x9a, 0xee, 0x66, 0x57, 0x5d, 0x00, 0x18,
	0x60, 0xdf, 0x90, 0x4b, 0xb5, 0x40, 0xc1, 0xa6, 0x6d, 0xb7, 0x52, 0x70, 0x59, 0x1d, 0xff, 0x45,
	0xea, 0x6d, 0x5a, 0xab, 0xad, 0xde, 0x81, 0xcb, 0xd2, 0x7b, 0x69, 0xbd, 0xbf, 0xf4, 0xfb, 0x5f,
	0x3c, 0xc4, 0xd5, 0x90, 0x77, 0x08, 0x0f, 0x8b, 0xe9, 0x4c, 0xb4, 0x76, 0x1c, 0x1b, 0x1f, 0x06,
	0x45, 0xef, 0x3a, 0x5e, 0x30, 0x50, 0xe7, 0x4f, 0xbe, 0xfd, 0x7a, 0x1b, 0x9d, 0x25, 0xaa, 0x2e,
	0x81, 0x7a, 0x0d, 0xa8, 0x87, 0x9f, 0x40, 0xf2, 0x11, 0xe1, 0xf1, 0xd0, 0x34, 0x20, 0xcb, 0x1d,
	0xcb, 0x35, 0x7b, 0x47, 0x94, 0x95, 0x5e, 0x61, 0x40, 0x36, 0xcd, 0xc9, 0xae, 0x93, 0xd5, 0x76,
	0x64, 0xeb, 0x5e, 0x66, 0xfd, 0x28, 0xf8, 0x5b, 0x3f, 0xf6, 0x45, 0x90, 0xc6, 0x09, 0x49, 0x56,
	0x7b, 0xa3, 0x14, 0x9c, 0xe0, 0xca, 0x5a, 0x5f, 0x58, 0xd0, 0x94, 0xe2, 0x9a, 0x16, 0xc8, 0x8d,
	0x1e, 0x34, 0x91, 0xf7, 0x08, 0x8f, 0x06, 0xa6, 0x1d, 0x49, 0x75, 0x64, 0xd0, 0x38, 0x51, 0x95,
	0xdb, 0xbd, 0x81, 0x80, 0xef, 0x1a, 0xe7, 0xbb, 0x4c, 0x52, 0xed, 0xf8, 0xfa, 0x24, 0x7d, 0xb2,
	0x9c, 0xb7, 0x7e, 0x04, 0x93, 0xfa, 0x98, 0x7c, 0x45, 0x78, 0xa2, 0xfe, 0x97, 0x45, 0x3a, 0xdb,
	0xd7, 0x7a, 0x1a, 0x2a, 0xeb, 0xfd, 0x81, 0x41, 0xcc, 0x06, 0x17, 0xb3, 0x4a, 0xee, 0x74, 0x69,
	0x3e, 0x4c, 0x5a, 0xfd, 0x08, 0x16, 0xc7, 0xe4, 0x14, 0xe1, 0xc9, 0xfa, 0xf4, 0x9b, 0xb6, 0xdd,
	0x85, 0xa8, 0xd6, 0x03, 0xb2, 0x0b, 0x51, 0x6d, 0x26, 0x9e, 0xba, 0xc2, 0x45, 0xdd, 0x22, 0x5a,
	0x6f, 0xa2, 0xd2, 0xdb, 0xa7, 0xe7, 0x09, 0x74, 0x76, 0x9e, 0x40, 0x3f, 0xcf, 0x13, 0xe8, 0xcd,
	0x45, 0x22, 0x72, 0x76, 0x91, 0x88, 0x7c, 0xbf, 0x48, 0x44, 0x9e, 0x2d, 0x14, 0x2d, 0x6f, 0xaf,
	0x92, 0xd3, 0x4c, 0xb6, 0xdf, 0x2c, 0xe7, 0x61, 0x2d, 0xab, 0x57, 0x2d, 0x51, 0x37, 0x37, 0xcc,
	0xff, 0xba, 0xa6, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0x34, 0xca, 0x81, 0xf0, 0xd4, 0x0b, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a ClassesByISCN by index.
	ClassesByISCN(ctx context.Context, in *QueryClassesByISCNRequest, opts ...grpc.CallOption) (*QueryClassesByISCNResponse, error)
	// Queries a list of ClassesByISCN items.
	ClassesByISCNIndex(ctx context.Context, in *QueryClassesByISCNIndexRequest, opts ...grpc.CallOption) (*QueryClassesByISCNIndexResponse, error)
	// Queries a list of ISCNByClass items.
	ISCNByClass(ctx context.Context, in *QueryISCNByClassRequest, opts ...grpc.CallOption) (*QueryISCNByClassResponse, error)
	// Queries a ClassesByAccount by index.
	ClassesByAccount(ctx context.Context, in *QueryGetClassesByAccountRequest, opts ...grpc.CallOption) (*QueryGetClassesByAccountResponse, error)
	// Queries a list of ClassesByAccount items.
	ClassesByAccountAll(ctx context.Context, in *QueryAllClassesByAccountRequest, opts ...grpc.CallOption) (*QueryAllClassesByAccountResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/likecoin.likechain.likenft.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClassesByISCN(ctx context.Context, in *QueryClassesByISCNRequest, opts ...grpc.CallOption) (*QueryClassesByISCNResponse, error) {
	out := new(QueryClassesByISCNResponse)
	err := c.cc.Invoke(ctx, "/likecoin.likechain.likenft.Query/ClassesByISCN", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClassesByISCNIndex(ctx context.Context, in *QueryClassesByISCNIndexRequest, opts ...grpc.CallOption) (*QueryClassesByISCNIndexResponse, error) {
	out := new(QueryClassesByISCNIndexResponse)
	err := c.cc.Invoke(ctx, "/likecoin.likechain.likenft.Query/ClassesByISCNIndex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ISCNByClass(ctx context.Context, in *QueryISCNByClassRequest, opts ...grpc.CallOption) (*QueryISCNByClassResponse, error) {
	out := new(QueryISCNByClassResponse)
	err := c.cc.Invoke(ctx, "/likecoin.likechain.likenft.Query/ISCNByClass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClassesByAccount(ctx context.Context, in *QueryGetClassesByAccountRequest, opts ...grpc.CallOption) (*QueryGetClassesByAccountResponse, error) {
	out := new(QueryGetClassesByAccountResponse)
	err := c.cc.Invoke(ctx, "/likecoin.likechain.likenft.Query/ClassesByAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ClassesByAccountAll(ctx context.Context, in *QueryAllClassesByAccountRequest, opts ...grpc.CallOption) (*QueryAllClassesByAccountResponse, error) {
	out := new(QueryAllClassesByAccountResponse)
	err := c.cc.Invoke(ctx, "/likecoin.likechain.likenft.Query/ClassesByAccountAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a ClassesByISCN by index.
	ClassesByISCN(context.Context, *QueryClassesByISCNRequest) (*QueryClassesByISCNResponse, error)
	// Queries a list of ClassesByISCN items.
	ClassesByISCNIndex(context.Context, *QueryClassesByISCNIndexRequest) (*QueryClassesByISCNIndexResponse, error)
	// Queries a list of ISCNByClass items.
	ISCNByClass(context.Context, *QueryISCNByClassRequest) (*QueryISCNByClassResponse, error)
	// Queries a ClassesByAccount by index.
	ClassesByAccount(context.Context, *QueryGetClassesByAccountRequest) (*QueryGetClassesByAccountResponse, error)
	// Queries a list of ClassesByAccount items.
	ClassesByAccountAll(context.Context, *QueryAllClassesByAccountRequest) (*QueryAllClassesByAccountResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ClassesByISCN(ctx context.Context, req *QueryClassesByISCNRequest) (*QueryClassesByISCNResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassesByISCN not implemented")
}
func (*UnimplementedQueryServer) ClassesByISCNIndex(ctx context.Context, req *QueryClassesByISCNIndexRequest) (*QueryClassesByISCNIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassesByISCNIndex not implemented")
}
func (*UnimplementedQueryServer) ISCNByClass(ctx context.Context, req *QueryISCNByClassRequest) (*QueryISCNByClassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ISCNByClass not implemented")
}
func (*UnimplementedQueryServer) ClassesByAccount(ctx context.Context, req *QueryGetClassesByAccountRequest) (*QueryGetClassesByAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassesByAccount not implemented")
}
func (*UnimplementedQueryServer) ClassesByAccountAll(ctx context.Context, req *QueryAllClassesByAccountRequest) (*QueryAllClassesByAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClassesByAccountAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/likecoin.likechain.likenft.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClassesByISCN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClassesByISCNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClassesByISCN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/likecoin.likechain.likenft.Query/ClassesByISCN",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClassesByISCN(ctx, req.(*QueryClassesByISCNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClassesByISCNIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryClassesByISCNIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClassesByISCNIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/likecoin.likechain.likenft.Query/ClassesByISCNIndex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClassesByISCNIndex(ctx, req.(*QueryClassesByISCNIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ISCNByClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryISCNByClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ISCNByClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/likecoin.likechain.likenft.Query/ISCNByClass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ISCNByClass(ctx, req.(*QueryISCNByClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClassesByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetClassesByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClassesByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/likecoin.likechain.likenft.Query/ClassesByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClassesByAccount(ctx, req.(*QueryGetClassesByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ClassesByAccountAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllClassesByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ClassesByAccountAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/likecoin.likechain.likenft.Query/ClassesByAccountAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ClassesByAccountAll(ctx, req.(*QueryAllClassesByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "likecoin.likechain.likenft.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ClassesByISCN",
			Handler:    _Query_ClassesByISCN_Handler,
		},
		{
			MethodName: "ClassesByISCNIndex",
			Handler:    _Query_ClassesByISCNIndex_Handler,
		},
		{
			MethodName: "ISCNByClass",
			Handler:    _Query_ISCNByClass_Handler,
		},
		{
			MethodName: "ClassesByAccount",
			Handler:    _Query_ClassesByAccount_Handler,
		},
		{
			MethodName: "ClassesByAccountAll",
			Handler:    _Query_ClassesByAccountAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "likenft/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryClassesByISCNRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClassesByISCNRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClassesByISCNRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.IscnIdPrefix) > 0 {
		i -= len(m.IscnIdPrefix)
		copy(dAtA[i:], m.IscnIdPrefix)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IscnIdPrefix)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClassesByISCNResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClassesByISCNResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClassesByISCNResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Classes) > 0 {
		for iNdEx := len(m.Classes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Classes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.IscnIdPrefix) > 0 {
		i -= len(m.IscnIdPrefix)
		copy(dAtA[i:], m.IscnIdPrefix)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IscnIdPrefix)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClassesByISCNIndexRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClassesByISCNIndexRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClassesByISCNIndexRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryClassesByISCNIndexResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryClassesByISCNIndexResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryClassesByISCNIndexResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClassesByISCN) > 0 {
		for iNdEx := len(m.ClassesByISCN) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClassesByISCN[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryISCNByClassRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryISCNByClassRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryISCNByClassRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClassId) > 0 {
		i -= len(m.ClassId)
		copy(dAtA[i:], m.ClassId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ClassId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryISCNByClassResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryISCNByClassResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryISCNByClassResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LatestRecord.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.LatestVersion != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LatestVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IscnIdPrefix) > 0 {
		i -= len(m.IscnIdPrefix)
		copy(dAtA[i:], m.IscnIdPrefix)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IscnIdPrefix)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetClassesByAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClassesByAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClassesByAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetClassesByAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetClassesByAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetClassesByAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ClassesByAccount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllClassesByAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllClassesByAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllClassesByAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllClassesByAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllClassesByAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllClassesByAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClassesByAccount) > 0 {
		for iNdEx := len(m.ClassesByAccount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClassesByAccount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryClassesByISCNRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IscnIdPrefix)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryClassesByISCNResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IscnIdPrefix)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Classes) > 0 {
		for _, e := range m.Classes {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryClassesByISCNIndexRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryClassesByISCNIndexResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ClassesByISCN) > 0 {
		for _, e := range m.ClassesByISCN {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryISCNByClassRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClassId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryISCNByClassResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IscnIdPrefix)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.LatestVersion != 0 {
		n += 1 + sovQuery(uint64(m.LatestVersion))
	}
	l = m.LatestRecord.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetClassesByAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetClassesByAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ClassesByAccount.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllClassesByAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllClassesByAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ClassesByAccount) > 0 {
		for _, e := range m.ClassesByAccount {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClassesByISCNRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClassesByISCNRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClassesByISCNRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IscnIdPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IscnIdPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClassesByISCNResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClassesByISCNResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClassesByISCNResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IscnIdPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IscnIdPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Classes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Classes = append(m.Classes, nft.Class{})
			if err := m.Classes[len(m.Classes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClassesByISCNIndexRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClassesByISCNIndexRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClassesByISCNIndexRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryClassesByISCNIndexResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryClassesByISCNIndexResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryClassesByISCNIndexResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassesByISCN", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassesByISCN = append(m.ClassesByISCN, ClassesByISCN{})
			if err := m.ClassesByISCN[len(m.ClassesByISCN)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryISCNByClassRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryISCNByClassRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryISCNByClassRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryISCNByClassResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryISCNByClassResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryISCNByClassResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IscnIdPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IscnIdPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestVersion", wireType)
			}
			m.LatestVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestRecord", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LatestRecord.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetClassesByAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClassesByAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClassesByAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetClassesByAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetClassesByAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetClassesByAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassesByAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClassesByAccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllClassesByAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllClassesByAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllClassesByAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllClassesByAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllClassesByAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllClassesByAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClassesByAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClassesByAccount = append(m.ClassesByAccount, ClassesByAccount{})
			if err := m.ClassesByAccount[len(m.ClassesByAccount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
